[package]
name = "dingo_geo"
version.workspace = true
edition.workspace = true

[dependencies]
dingo_core = { path = "../core" }
geo.workspace = true
geojson.workspace = true
thiserror.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true
