[package]
name = "dingo_enrich"
version.workspace = true
edition.workspace = true

[dependencies]
dingo_core = { path = "../core" }
reqwest.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
sqlx.workspace = true
uuid.workspace = true
sunrise = "2"
osmpbf.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
